### ISSUE TITLE
详情页增加用于分享的区域

### ISSUE THREAD

**Issue by pheye** [pheye/wepy-mall#17]
使用这个小程序试下它的功能，我们希望用户点击分享后能像这个小程序一样触发分享菜单。
左边的头像你取6个头像，每次进入随机生成3张显示即可。。

![image](https://user-images.githubusercontent.com/24363168/55664456-68363b00-5860-11e9-8264-2513a4b7b799.png)

**Comment by loulonglong** [comment]
1.这个APP是之前给我的那个小程序吗，没有看到这个部分功能。
2.分享的按钮做在哪里，是邀请好友一起抢这边吗？分享菜单有哪些功能呢？
3.用户的数据是先模拟6个随机显示3个吗？

**Comment by pheye** [comment]
确认解决。
