### ISSUE TITLE
带产品变量的产品，在加入购物车以后，购物车应该提示用户购买的产品变量规格

### ISSUE THREAD

**Issue by pheye** [pheye/wepy-mall#32]
如图，产品详情页这个产品有多个产品变量，但是购买以后，购物车看不出是买的是哪个，购物车需要优化下。

![image](https://user-images.githubusercontent.com/24363168/56328238-7b2a0300-61b0-11e9-8297-b58d0d52b99a.png)

**Comment by pheye** [comment]
进入确认订单时，商品的提示也要跟着修改。

![image](https://user-images.githubusercontent.com/24363168/56333647-905e5c00-61c7-11e9-98ec-c6b07e6c30a5.png)

**Comment by pheye** [comment]
已经合并，然后合并请求有问题，需要优化处理。

**Comment by loulonglong** [comment]
已完成请检查
