### ISSUE TITLE
集成统计功能

### ISSUE THREAD

**Issue by pheye** [pheye/wepy-mall#64]
1.了解统计平台的作用
2.然后集成到小程序中
3.你在测试时如果未勾选 “不检查域名。。。”那个项，会发现域名被阻塞，将域名告诉我，我来添加

统计平台：
https://tj.aldwx.com/

我已经给你的手机号发送邀请，项目我已经建好，不要重复创建。

**Comment by loulonglong** [comment]
阻塞的域名：https://log.aldwx.com

**Comment by pheye** [comment]
添加了，重启即可。

**Comment by pheye** [comment]
确认已经添加。
